# Generated by Django 2.0.2 on 2018-04-24 15:38

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_session_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(),
        ),
    ]
