# Generated by Django 2.0.2 on 2018-04-18 13:17

from django.db import migrations
import django.db.models.functions.base


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180413_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': [django.db.models.functions.base.Lower('name')]},
        ),
    ]
