# Generated by Django 2.0.2 on 2018-04-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180418_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='start',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
