# Generated by Django 2.0.2 on 2018-05-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project_order',
            field=models.CharField(choices=[('TD', 'Total Duration'), ('LD', 'Last Done')], default='TD', max_length=2),
        ),
    ]
